version: '3.8'
services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hms_db
    ports:
      - "5432:5432"

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://root:root@postgres:5432/hms_db"
      JWT_SECRET: "fa;dlkfafblfjdafA:df;alkajfd;s"
      SECRET: "adsf;lkjakf'ojadfsadsf;kdfl;jaldfdsflk;"

volumes:
  postgres_data:
